// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.MemoryAddress;
import jdk.incubator.foreign.MemoryLayout;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;
import jdk.incubator.foreign.SegmentAllocator;

import java.lang.invoke.VarHandle;

import static jdk.incubator.foreign.CLinker.C_CHAR;
import static jdk.incubator.foreign.CLinker.C_INT;

public class __mbstate_t {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
            C_INT.withName("__count"),
            MemoryLayout.unionLayout(
                    C_INT.withName("__wch"),
                    MemoryLayout.sequenceLayout(4, C_CHAR).withName("__wchb")
            ).withName("__value")
    );
    static final VarHandle __count$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("__count"));

    public static MemoryLayout $LAYOUT() {
        return __mbstate_t.$struct$LAYOUT;
    }

    public static VarHandle __count$VH() {
        return __mbstate_t.__count$VH;
    }

    public static int __count$get(MemorySegment seg) {
        return (int) __mbstate_t.__count$VH.get(seg);
    }

    public static void __count$set(MemorySegment seg, int x) {
        __mbstate_t.__count$VH.set(seg, x);
    }

    public static int __count$get(MemorySegment seg, long index) {
        return (int) __mbstate_t.__count$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void __count$set(MemorySegment seg, long index, int x) {
        __mbstate_t.__count$VH.set(seg.asSlice(index * sizeof()), x);
    }

    public static MemorySegment __value$slice(MemorySegment seg) {
        return seg.asSlice(4, 4);
    }

    public static long sizeof() {
        return $LAYOUT().byteSize();
    }

    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate($LAYOUT());
    }

    public static MemorySegment allocate(ResourceScope scope) {
        return allocate(SegmentAllocator.ofScope(scope));
    }

    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }

    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope);
    }

    public static class __value {

        static final MemoryLayout __value$union$LAYOUT = MemoryLayout.unionLayout(
                C_INT.withName("__wch"),
                MemoryLayout.sequenceLayout(4, C_CHAR).withName("__wchb")
        );
        static final VarHandle __wch$VH = __value$union$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("__wch"));

        public static MemoryLayout $LAYOUT() {
            return __value.__value$union$LAYOUT;
        }

        public static VarHandle __wch$VH() {
            return __value.__wch$VH;
        }

        public static int __wch$get(MemorySegment seg) {
            return (int) __value.__wch$VH.get(seg);
        }

        public static void __wch$set(MemorySegment seg, int x) {
            __value.__wch$VH.set(seg, x);
        }

        public static int __wch$get(MemorySegment seg, long index) {
            return (int) __value.__wch$VH.get(seg.asSlice(index * sizeof()));
        }

        public static void __wch$set(MemorySegment seg, long index, int x) {
            __value.__wch$VH.set(seg.asSlice(index * sizeof()), x);
        }

        public static MemorySegment __wchb$slice(MemorySegment seg) {
            return seg.asSlice(0, 4);
        }

        public static long sizeof() {
            return $LAYOUT().byteSize();
        }

        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate($LAYOUT());
        }

        public static MemorySegment allocate(ResourceScope scope) {
            return allocate(SegmentAllocator.ofScope(scope));
        }

        public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }

        public static MemorySegment allocateArray(int len, ResourceScope scope) {
            return allocateArray(len, SegmentAllocator.ofScope(scope));
        }

        public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) {
            return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope);
        }
    }
}


