// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_LONG_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$6 {

    static final FunctionDescriptor rindex$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_INT
    );
    static final MethodHandle rindex$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "rindex",
            "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
            constants$6.rindex$FUNC, false
    );
    static final FunctionDescriptor ffs$FUNC = FunctionDescriptor.of(C_INT,
            C_INT
    );
    static final MethodHandle ffs$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ffs",
            "(I)I",
            constants$6.ffs$FUNC, false
    );
    static final FunctionDescriptor ffsl$FUNC = FunctionDescriptor.of(C_INT,
            C_LONG
    );
    static final MethodHandle ffsl$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ffsl",
            "(J)I",
            constants$6.ffsl$FUNC, false
    );
    static final FunctionDescriptor ffsll$FUNC = FunctionDescriptor.of(C_INT,
            C_LONG_LONG
    );
    static final MethodHandle ffsll$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ffsll",
            "(J)I",
            constants$6.ffsll$FUNC, false
    );
    static final FunctionDescriptor strcasecmp$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strcasecmp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strcasecmp",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$6.strcasecmp$FUNC, false
    );
    static final FunctionDescriptor strncasecmp$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle strncasecmp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strncasecmp",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
            constants$6.strncasecmp$FUNC, false
    );
}


