// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$85 {

    static final FunctionDescriptor roundf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle roundf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "roundf",
            "(F)F",
            constants$85.roundf$FUNC, false
    );
    static final FunctionDescriptor __roundf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __roundf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__roundf",
            "(F)F",
            constants$85.__roundf$FUNC, false
    );
    static final FunctionDescriptor truncf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle truncf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "truncf",
            "(F)F",
            constants$85.truncf$FUNC, false
    );
    static final FunctionDescriptor __truncf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __truncf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__truncf",
            "(F)F",
            constants$85.__truncf$FUNC, false
    );
    static final FunctionDescriptor remquof$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT,
            C_POINTER
    );
    static final MethodHandle remquof$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "remquof",
            "(FFLjdk/incubator/foreign/MemoryAddress;)F",
            constants$85.remquof$FUNC, false
    );
    static final FunctionDescriptor __remquof$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT,
            C_POINTER
    );
    static final MethodHandle __remquof$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__remquof",
            "(FFLjdk/incubator/foreign/MemoryAddress;)F",
            constants$85.__remquof$FUNC, false
    );
}


