// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$110 {

    static final MemorySegment PRIu8$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIu16$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIu32$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIu64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuLEAST8$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuLEAST16$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
}


