// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_LONG_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$23 {

    static final FunctionDescriptor __ctype_get_mb_cur_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle __ctype_get_mb_cur_max$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__ctype_get_mb_cur_max",
            "()J",
            constants$23.__ctype_get_mb_cur_max$FUNC, false
    );
    static final FunctionDescriptor atof$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle atof$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "atof",
            "(Ljdk/incubator/foreign/MemoryAddress;)D",
            constants$23.atof$FUNC, false
    );
    static final FunctionDescriptor atoi$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle atoi$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "atoi",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$23.atoi$FUNC, false
    );
    static final FunctionDescriptor atol$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER
    );
    static final MethodHandle atol$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "atol",
            "(Ljdk/incubator/foreign/MemoryAddress;)J",
            constants$23.atol$FUNC, false
    );
    static final FunctionDescriptor atoll$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_POINTER
    );
    static final MethodHandle atoll$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "atoll",
            "(Ljdk/incubator/foreign/MemoryAddress;)J",
            constants$23.atoll$FUNC, false
    );
    static final FunctionDescriptor strtod$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strtod$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strtod",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)D",
            constants$23.strtod$FUNC, false
    );
}


