// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$122 {

    static final MemorySegment SCNu8$SEGMENT = CLinker.toCString("hhu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNu16$SEGMENT = CLinker.toCString("hu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNu32$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment SCNu64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuLEAST8$SEGMENT = CLinker.toCString("hhu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuLEAST16$SEGMENT = CLinker.toCString("hu", ResourceScope.newImplicitScope());
}


