// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;

class constants$81 {

    static final FunctionDescriptor erfcf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle erfcf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "erfcf",
            "(F)F",
            constants$81.erfcf$FUNC, false
    );
    static final FunctionDescriptor __erfcf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __erfcf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__erfcf",
            "(F)F",
            constants$81.__erfcf$FUNC, false
    );
    static final FunctionDescriptor lgammaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle lgammaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lgammaf",
            "(F)F",
            constants$81.lgammaf$FUNC, false
    );
    static final FunctionDescriptor __lgammaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __lgammaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lgammaf",
            "(F)F",
            constants$81.__lgammaf$FUNC, false
    );
    static final FunctionDescriptor tgammaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle tgammaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "tgammaf",
            "(F)F",
            constants$81.tgammaf$FUNC, false
    );
    static final FunctionDescriptor __tgammaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __tgammaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__tgammaf",
            "(F)F",
            constants$81.__tgammaf$FUNC, false
    );
}


