// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;

class constants$51 {

    static final FunctionDescriptor __hypot$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __hypot$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__hypot",
            "(DD)D",
            constants$51.__hypot$FUNC, false
    );
    static final FunctionDescriptor cbrt$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle cbrt$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "cbrt",
            "(D)D",
            constants$51.cbrt$FUNC, false
    );
    static final FunctionDescriptor __cbrt$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __cbrt$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__cbrt",
            "(D)D",
            constants$51.__cbrt$FUNC, false
    );
    static final FunctionDescriptor ceil$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle ceil$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ceil",
            "(D)D",
            constants$51.ceil$FUNC, false
    );
    static final FunctionDescriptor __ceil$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __ceil$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__ceil",
            "(D)D",
            constants$51.__ceil$FUNC, false
    );
    static final FunctionDescriptor fabs$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle fabs$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fabs",
            "(D)D",
            constants$51.fabs$FUNC, false
    );
}


