// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$129 {

    static final MemorySegment SCNiPTR$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoPTR$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuPTR$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxPTR$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment LIBRAW_VERSION_STR$SEGMENT = CLinker.toCString("0.20.2-Release", ResourceScope.newImplicitScope());
}


