// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$113 {

    static final MemorySegment PRIxLEAST32$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxLEAST64$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxFAST8$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxFAST16$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxFAST32$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxFAST64$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
}


