// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$47 {

    static final FunctionDescriptor __frexp$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle __frexp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__frexp",
            "(DLjdk/incubator/foreign/MemoryAddress;)D",
            constants$47.__frexp$FUNC, false
    );
    static final FunctionDescriptor ldexp$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_INT
    );
    static final MethodHandle ldexp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ldexp",
            "(DI)D",
            constants$47.ldexp$FUNC, false
    );
    static final FunctionDescriptor __ldexp$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_INT
    );
    static final MethodHandle __ldexp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__ldexp",
            "(DI)D",
            constants$47.__ldexp$FUNC, false
    );
    static final FunctionDescriptor log$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle log$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "log",
            "(D)D",
            constants$47.log$FUNC, false
    );
    static final FunctionDescriptor __log$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __log$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__log",
            "(D)D",
            constants$47.__log$FUNC, false
    );
    static final FunctionDescriptor log10$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle log10$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "log10",
            "(D)D",
            constants$47.log10$FUNC, false
    );
}


