// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$108 {

    static final MemorySegment PRIo8$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIo16$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIo32$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIo64$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoLEAST8$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoLEAST16$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
}


