// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$104 {

    static final MemorySegment PRId8$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRId16$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRId32$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRId64$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdLEAST8$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdLEAST16$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
}


