// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$11 {

    static final FunctionDescriptor fdopen$FUNC = FunctionDescriptor.of(C_POINTER,
            C_INT,
            C_POINTER
    );
    static final MethodHandle fdopen$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fdopen",
            "(ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$11.fdopen$FUNC, false
    );
    static final FunctionDescriptor fmemopen$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle fmemopen$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fmemopen",
            "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$11.fmemopen$FUNC, false
    );
    static final FunctionDescriptor open_memstream$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle open_memstream$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "open_memstream",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$11.open_memstream$FUNC, false
    );
    static final FunctionDescriptor setbuf$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle setbuf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setbuf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$11.setbuf$FUNC, false
    );
    static final FunctionDescriptor setvbuf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_INT,
            C_LONG
    );
    static final MethodHandle setvbuf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setvbuf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IJ)I",
            constants$11.setvbuf$FUNC, false
    );
    static final FunctionDescriptor setbuffer$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle setbuffer$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setbuffer",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)V",
            constants$11.setbuffer$FUNC, false
    );
}


