// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$17 {

    static final FunctionDescriptor putw$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER
    );
    static final MethodHandle putw$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "putw",
            "(ILjdk/incubator/foreign/MemoryAddress;)I",
            constants$17.putw$FUNC, false
    );
    static final FunctionDescriptor fgets$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_INT,
            C_POINTER
    );
    static final MethodHandle fgets$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fgets",
            "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$17.fgets$FUNC, false
    );
    static final FunctionDescriptor __getdelim$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_POINTER,
            C_INT,
            C_POINTER
    );
    static final MethodHandle __getdelim$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__getdelim",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)J",
            constants$17.__getdelim$FUNC, false
    );
    static final FunctionDescriptor getdelim$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_POINTER,
            C_INT,
            C_POINTER
    );
    static final MethodHandle getdelim$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "getdelim",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)J",
            constants$17.getdelim$FUNC, false
    );
    static final FunctionDescriptor getline$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle getline$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "getline",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
            constants$17.getline$FUNC, false
    );
    static final FunctionDescriptor fputs$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle fputs$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fputs",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$17.fputs$FUNC, false
    );
}


