// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$36 {

    static final FunctionDescriptor clearenv$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle clearenv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "clearenv",
            "()I",
            constants$36.clearenv$FUNC, false
    );
    static final FunctionDescriptor mktemp$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle mktemp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mktemp",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$36.mktemp$FUNC, false
    );
    static final FunctionDescriptor mkstemp$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle mkstemp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mkstemp",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$36.mkstemp$FUNC, false
    );
    static final FunctionDescriptor mkstemps$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_INT
    );
    static final MethodHandle mkstemps$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mkstemps",
            "(Ljdk/incubator/foreign/MemoryAddress;I)I",
            constants$36.mkstemps$FUNC, false
    );
    static final FunctionDescriptor mkdtemp$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle mkdtemp$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mkdtemp",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$36.mkdtemp$FUNC, false
    );
    static final FunctionDescriptor system$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle system$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "system",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$36.system$FUNC, false
    );
}


