// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;

class constants$59 {

    static final FunctionDescriptor nextafter$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle nextafter$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "nextafter",
            "(DD)D",
            constants$59.nextafter$FUNC, false
    );
    static final FunctionDescriptor __nextafter$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __nextafter$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__nextafter",
            "(DD)D",
            constants$59.__nextafter$FUNC, false
    );
    static final FunctionDescriptor remainder$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle remainder$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "remainder",
            "(DD)D",
            constants$59.remainder$FUNC, false
    );
    static final FunctionDescriptor __remainder$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __remainder$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__remainder",
            "(DD)D",
            constants$59.__remainder$FUNC, false
    );
    static final FunctionDescriptor scalbn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_INT
    );
    static final MethodHandle scalbn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scalbn",
            "(DI)D",
            constants$59.scalbn$FUNC, false
    );
    static final FunctionDescriptor __scalbn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_INT
    );
    static final MethodHandle __scalbn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__scalbn",
            "(DI)D",
            constants$59.__scalbn$FUNC, false
    );
}


