// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$117 {

    static final MemorySegment PRIdPTR$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIiPTR$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoPTR$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuPTR$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxPTR$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXPTR$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
}


