// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$127 {

    static final MemorySegment SCNxLEAST32$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxLEAST64$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxFAST8$SEGMENT = CLinker.toCString("hhx", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxFAST16$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxFAST32$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment SCNxFAST64$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
}


