// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$18 {

    static final FunctionDescriptor puts$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle puts$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "puts",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$18.puts$FUNC, false
    );
    static final FunctionDescriptor ungetc$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER
    );
    static final MethodHandle ungetc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ungetc",
            "(ILjdk/incubator/foreign/MemoryAddress;)I",
            constants$18.ungetc$FUNC, false
    );
    static final FunctionDescriptor fread$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_LONG,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle fread$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fread",
            "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)J",
            constants$18.fread$FUNC, false
    );
    static final FunctionDescriptor fwrite$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_LONG,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle fwrite$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fwrite",
            "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)J",
            constants$18.fwrite$FUNC, false
    );
    static final FunctionDescriptor fread_unlocked$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_LONG,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle fread_unlocked$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fread_unlocked",
            "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)J",
            constants$18.fread_unlocked$FUNC, false
    );
    static final FunctionDescriptor fwrite_unlocked$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_LONG,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle fwrite_unlocked$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fwrite_unlocked",
            "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)J",
            constants$18.fwrite_unlocked$FUNC, false
    );
}


