// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$114 {

    static final MemorySegment PRIX8$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIX16$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIX32$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIX64$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXLEAST8$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXLEAST16$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
}


