// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_LONG_LONG;

class constants$62 {

    static final FunctionDescriptor lrint$FUNC = FunctionDescriptor.of(C_LONG,
            C_DOUBLE
    );
    static final MethodHandle lrint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lrint",
            "(D)J",
            constants$62.lrint$FUNC, false
    );
    static final FunctionDescriptor __lrint$FUNC = FunctionDescriptor.of(C_LONG,
            C_DOUBLE
    );
    static final MethodHandle __lrint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lrint",
            "(D)J",
            constants$62.__lrint$FUNC, false
    );
    static final FunctionDescriptor llrint$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_DOUBLE
    );
    static final MethodHandle llrint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "llrint",
            "(D)J",
            constants$62.llrint$FUNC, false
    );
    static final FunctionDescriptor __llrint$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_DOUBLE
    );
    static final MethodHandle __llrint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__llrint",
            "(D)J",
            constants$62.__llrint$FUNC, false
    );
    static final FunctionDescriptor lround$FUNC = FunctionDescriptor.of(C_LONG,
            C_DOUBLE
    );
    static final MethodHandle lround$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lround",
            "(D)J",
            constants$62.lround$FUNC, false
    );
    static final FunctionDescriptor __lround$FUNC = FunctionDescriptor.of(C_LONG,
            C_DOUBLE
    );
    static final MethodHandle __lround$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lround",
            "(D)J",
            constants$62.__lround$FUNC, false
    );
}


