// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$30 {

    static final FunctionDescriptor lcong48$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle lcong48$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lcong48",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$30.lcong48$FUNC, false
    );
    static final FunctionDescriptor drand48_r$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle drand48_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "drand48_r",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$30.drand48_r$FUNC, false
    );
    static final FunctionDescriptor erand48_r$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle erand48_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "erand48_r",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$30.erand48_r$FUNC, false
    );
    static final FunctionDescriptor lrand48_r$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle lrand48_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lrand48_r",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$30.lrand48_r$FUNC, false
    );
    static final FunctionDescriptor nrand48_r$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle nrand48_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "nrand48_r",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$30.nrand48_r$FUNC, false
    );
    static final FunctionDescriptor mrand48_r$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle mrand48_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mrand48_r",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$30.mrand48_r$FUNC, false
    );
}


