// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$93 {

    static final FunctionDescriptor progress_callback$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_INT,
            C_INT,
            C_INT
    );
    static final MethodHandle progress_callback$MH = RuntimeHelper.downcallHandle(
            "(Ljdk/incubator/foreign/MemoryAddress;III)I",
            constants$93.progress_callback$FUNC, false
    );
    static final FunctionDescriptor pre_identify_callback$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle pre_identify_callback$MH = RuntimeHelper.downcallHandle(
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$93.pre_identify_callback$FUNC, false
    );
    static final FunctionDescriptor post_identify_callback$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle post_identify_callback$MH = RuntimeHelper.downcallHandle(
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$93.post_identify_callback$FUNC, false
    );
}


