// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$3 {

    static final FunctionDescriptor strchr$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_INT
    );
    static final MethodHandle strchr$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strchr",
            "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
            constants$3.strchr$FUNC, false
    );
    static final FunctionDescriptor strrchr$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_INT
    );
    static final MethodHandle strrchr$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strrchr",
            "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
            constants$3.strrchr$FUNC, false
    );
    static final FunctionDescriptor strcspn$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strcspn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strcspn",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
            constants$3.strcspn$FUNC, false
    );
    static final FunctionDescriptor strspn$FUNC = FunctionDescriptor.of(C_LONG,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strspn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strspn",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
            constants$3.strspn$FUNC, false
    );
    static final FunctionDescriptor strpbrk$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strpbrk$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strpbrk",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$3.strpbrk$FUNC, false
    );
    static final FunctionDescriptor strstr$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strstr$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strstr",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$3.strstr$FUNC, false
    );
}


