// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$99 {

    static final FunctionDescriptor libraw_dcraw_thumb_writer$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_thumb_writer$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_thumb_writer",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$99.libraw_dcraw_thumb_writer$FUNC, false
    );
    static final FunctionDescriptor libraw_dcraw_process$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_process$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_process",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$99.libraw_dcraw_process$FUNC, false
    );
    static final FunctionDescriptor libraw_dcraw_make_mem_image$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_make_mem_image$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_make_mem_image",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$99.libraw_dcraw_make_mem_image$FUNC, false
    );
    static final FunctionDescriptor libraw_dcraw_make_mem_thumb$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_make_mem_thumb$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_make_mem_thumb",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$99.libraw_dcraw_make_mem_thumb$FUNC, false
    );
    static final FunctionDescriptor libraw_dcraw_clear_mem$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_clear_mem$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_clear_mem",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$99.libraw_dcraw_clear_mem$FUNC, false
    );
    static final FunctionDescriptor libraw_set_demosaic$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_demosaic$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_demosaic",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$99.libraw_set_demosaic$FUNC, false
    );
}


