// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$12 {

    static final FunctionDescriptor setlinebuf$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle setlinebuf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setlinebuf",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$12.setlinebuf$FUNC, false
    );
    static final FunctionDescriptor fprintf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle fprintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fprintf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
            constants$12.fprintf$FUNC, true
    );
    static final FunctionDescriptor printf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle printf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "printf",
            "(Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
            constants$12.printf$FUNC, true
    );
    static final FunctionDescriptor sprintf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle sprintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "sprintf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
            constants$12.sprintf$FUNC, true
    );
    static final FunctionDescriptor vfprintf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle vfprintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "vfprintf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$12.vfprintf$FUNC, false
    );
    static final FunctionDescriptor vprintf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle vprintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "vprintf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$12.vprintf$FUNC, false
    );
}


