// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_LONG_LONG;

class constants$86 {

    static final FunctionDescriptor lrintf$FUNC = FunctionDescriptor.of(C_LONG,
            C_FLOAT
    );
    static final MethodHandle lrintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lrintf",
            "(F)J",
            constants$86.lrintf$FUNC, false
    );
    static final FunctionDescriptor __lrintf$FUNC = FunctionDescriptor.of(C_LONG,
            C_FLOAT
    );
    static final MethodHandle __lrintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lrintf",
            "(F)J",
            constants$86.__lrintf$FUNC, false
    );
    static final FunctionDescriptor llrintf$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_FLOAT
    );
    static final MethodHandle llrintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "llrintf",
            "(F)J",
            constants$86.llrintf$FUNC, false
    );
    static final FunctionDescriptor __llrintf$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_FLOAT
    );
    static final MethodHandle __llrintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__llrintf",
            "(F)J",
            constants$86.__llrintf$FUNC, false
    );
    static final FunctionDescriptor lroundf$FUNC = FunctionDescriptor.of(C_LONG,
            C_FLOAT
    );
    static final MethodHandle lroundf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lroundf",
            "(F)J",
            constants$86.lroundf$FUNC, false
    );
    static final FunctionDescriptor __lroundf$FUNC = FunctionDescriptor.of(C_LONG,
            C_FLOAT
    );
    static final MethodHandle __lroundf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lroundf",
            "(F)J",
            constants$86.__lroundf$FUNC, false
    );
}


