// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;
import static jdk.incubator.foreign.CLinker.C_SHORT;

class constants$26 {

    static final FunctionDescriptor __uint16_identity$FUNC = FunctionDescriptor.of(C_SHORT,
            C_SHORT
    );
    static final MethodHandle __uint16_identity$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__uint16_identity",
            "(S)S",
            constants$26.__uint16_identity$FUNC, false
    );
    static final FunctionDescriptor __uint32_identity$FUNC = FunctionDescriptor.of(C_INT,
            C_INT
    );
    static final MethodHandle __uint32_identity$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__uint32_identity",
            "(I)I",
            constants$26.__uint32_identity$FUNC, false
    );
    static final FunctionDescriptor __uint64_identity$FUNC = FunctionDescriptor.of(C_LONG,
            C_LONG
    );
    static final MethodHandle __uint64_identity$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__uint64_identity",
            "(J)J",
            constants$26.__uint64_identity$FUNC, false
    );
    static final FunctionDescriptor select$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle select$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "select",
            "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$26.select$FUNC, false
    );
    static final FunctionDescriptor pselect$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle pselect$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "pselect",
            "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$26.pselect$FUNC, false
    );
    static final FunctionDescriptor random$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle random$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "random",
            "()J",
            constants$26.random$FUNC, false
    );
}


