// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;

class constants$57 {

    static final FunctionDescriptor erfc$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle erfc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "erfc",
            "(D)D",
            constants$57.erfc$FUNC, false
    );
    static final FunctionDescriptor __erfc$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __erfc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__erfc",
            "(D)D",
            constants$57.__erfc$FUNC, false
    );
    static final FunctionDescriptor lgamma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle lgamma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lgamma",
            "(D)D",
            constants$57.lgamma$FUNC, false
    );
    static final FunctionDescriptor __lgamma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __lgamma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__lgamma",
            "(D)D",
            constants$57.__lgamma$FUNC, false
    );
    static final FunctionDescriptor tgamma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle tgamma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "tgamma",
            "(D)D",
            constants$57.tgamma$FUNC, false
    );
    static final FunctionDescriptor __tgamma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __tgamma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__tgamma",
            "(D)D",
            constants$57.__tgamma$FUNC, false
    );
}


