// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;

class constants$84 {

    static final FunctionDescriptor ilogbf$FUNC = FunctionDescriptor.of(C_INT,
            C_FLOAT
    );
    static final MethodHandle ilogbf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ilogbf",
            "(F)I",
            constants$84.ilogbf$FUNC, false
    );
    static final FunctionDescriptor __ilogbf$FUNC = FunctionDescriptor.of(C_INT,
            C_FLOAT
    );
    static final MethodHandle __ilogbf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__ilogbf",
            "(F)I",
            constants$84.__ilogbf$FUNC, false
    );
    static final FunctionDescriptor scalblnf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_LONG
    );
    static final MethodHandle scalblnf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scalblnf",
            "(FJ)F",
            constants$84.scalblnf$FUNC, false
    );
    static final FunctionDescriptor __scalblnf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_LONG
    );
    static final MethodHandle __scalblnf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__scalblnf",
            "(FJ)F",
            constants$84.__scalblnf$FUNC, false
    );
    static final FunctionDescriptor nearbyintf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle nearbyintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "nearbyintf",
            "(F)F",
            constants$84.nearbyintf$FUNC, false
    );
    static final FunctionDescriptor __nearbyintf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __nearbyintf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__nearbyintf",
            "(F)F",
            constants$84.__nearbyintf$FUNC, false
    );
}


