// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$9 {

    static final FunctionDescriptor remove$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle remove$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "remove",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$9.remove$FUNC, false
    );
    static final FunctionDescriptor rename$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle rename$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "rename",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$9.rename$FUNC, false
    );
    static final FunctionDescriptor renameat$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER,
            C_INT,
            C_POINTER
    );
    static final MethodHandle renameat$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "renameat",
            "(ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
            constants$9.renameat$FUNC, false
    );
    static final FunctionDescriptor tmpfile$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle tmpfile$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "tmpfile",
            "()Ljdk/incubator/foreign/MemoryAddress;",
            constants$9.tmpfile$FUNC, false
    );
    static final FunctionDescriptor tmpnam$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle tmpnam$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "tmpnam",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$9.tmpnam$FUNC, false
    );
    static final FunctionDescriptor tmpnam_r$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle tmpnam_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "tmpnam_r",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$9.tmpnam_r$FUNC, false
    );
}


