// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$35 {

    static final FunctionDescriptor quick_exit$FUNC = FunctionDescriptor.ofVoid(
            C_INT
    );
    static final MethodHandle quick_exit$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "quick_exit",
            "(I)V",
            constants$35.quick_exit$FUNC, false
    );
    static final FunctionDescriptor _Exit$FUNC = FunctionDescriptor.ofVoid(
            C_INT
    );
    static final MethodHandle _Exit$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "_Exit",
            "(I)V",
            constants$35._Exit$FUNC, false
    );
    static final FunctionDescriptor getenv$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle getenv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "getenv",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$35.getenv$FUNC, false
    );
    static final FunctionDescriptor putenv$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle putenv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "putenv",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$35.putenv$FUNC, false
    );
    static final FunctionDescriptor setenv$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_INT
    );
    static final MethodHandle setenv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setenv",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
            constants$35.setenv$FUNC, false
    );
    static final FunctionDescriptor unsetenv$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle unsetenv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "unsetenv",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$35.unsetenv$FUNC, false
    );
}


