// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$116 {

    static final MemorySegment PRIdMAX$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIiMAX$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoMAX$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuMAX$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxMAX$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXMAX$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
}


