// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$96 {

    static final FunctionDescriptor libraw_close$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle libraw_close$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_close",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$96.libraw_close$FUNC, false
    );
    static final FunctionDescriptor libraw_subtract_black$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle libraw_subtract_black$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_subtract_black",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$96.libraw_subtract_black$FUNC, false
    );
    static final FunctionDescriptor libraw_raw2image$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_raw2image$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_raw2image",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$96.libraw_raw2image$FUNC, false
    );
    static final FunctionDescriptor libraw_free_image$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle libraw_free_image$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_free_image",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$96.libraw_free_image$FUNC, false
    );
    static final FunctionDescriptor libraw_version$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle libraw_version$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_version",
            "([Ljava/lang/Object;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$96.libraw_version$FUNC, true
    );
    static final FunctionDescriptor libraw_versionNumber$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle libraw_versionNumber$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_versionNumber",
            "([Ljava/lang/Object;)I",
            constants$96.libraw_versionNumber$FUNC, true
    );
}


