// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$100 {

    static final FunctionDescriptor libraw_set_output_color$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_output_color$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_output_color",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$100.libraw_set_output_color$FUNC, false
    );
    static final FunctionDescriptor libraw_set_user_mul$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT,
            C_FLOAT
    );
    static final MethodHandle libraw_set_user_mul$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_user_mul",
            "(Ljdk/incubator/foreign/MemoryAddress;IF)V",
            constants$100.libraw_set_user_mul$FUNC, false
    );
    static final FunctionDescriptor libraw_set_output_bps$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_output_bps$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_output_bps",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$100.libraw_set_output_bps$FUNC, false
    );
    static final FunctionDescriptor libraw_set_gamma$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT,
            C_FLOAT
    );
    static final MethodHandle libraw_set_gamma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_gamma",
            "(Ljdk/incubator/foreign/MemoryAddress;IF)V",
            constants$100.libraw_set_gamma$FUNC, false
    );
    static final FunctionDescriptor libraw_set_no_auto_bright$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_no_auto_bright$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_no_auto_bright",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$100.libraw_set_no_auto_bright$FUNC, false
    );
    static final FunctionDescriptor libraw_set_bright$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_FLOAT
    );
    static final MethodHandle libraw_set_bright$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_bright",
            "(Ljdk/incubator/foreign/MemoryAddress;F)V",
            constants$100.libraw_set_bright$FUNC, false
    );
}


