// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.Addressable;
import jdk.incubator.foreign.MemoryAddress;
import jdk.incubator.foreign.ResourceScope;

public interface pre_identify_callback {

    static MemoryAddress allocate(pre_identify_callback fi) {
        return RuntimeHelper.upcallStub(pre_identify_callback.class, fi, constants$93.pre_identify_callback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
    }

    static MemoryAddress allocate(pre_identify_callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(pre_identify_callback.class, fi, constants$93.pre_identify_callback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }

    static pre_identify_callback ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int) constants$93.pre_identify_callback$MH.invokeExact((Addressable) addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }

    int apply(jdk.incubator.foreign.MemoryAddress x0);
}


