// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$115 {

    static final MemorySegment PRIXLEAST32$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXLEAST64$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXFAST8$SEGMENT = CLinker.toCString("X", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXFAST16$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXFAST32$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
    static final MemorySegment PRIXFAST64$SEGMENT = CLinker.toCString("lX", ResourceScope.newImplicitScope());
}


