// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;

class constants$60 {

    static final FunctionDescriptor ilogb$FUNC = FunctionDescriptor.of(C_INT,
            C_DOUBLE
    );
    static final MethodHandle ilogb$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ilogb",
            "(D)I",
            constants$60.ilogb$FUNC, false
    );
    static final FunctionDescriptor __ilogb$FUNC = FunctionDescriptor.of(C_INT,
            C_DOUBLE
    );
    static final MethodHandle __ilogb$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__ilogb",
            "(D)I",
            constants$60.__ilogb$FUNC, false
    );
    static final FunctionDescriptor scalbln$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_LONG
    );
    static final MethodHandle scalbln$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scalbln",
            "(DJ)D",
            constants$60.scalbln$FUNC, false
    );
    static final FunctionDescriptor __scalbln$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_LONG
    );
    static final MethodHandle __scalbln$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__scalbln",
            "(DJ)D",
            constants$60.__scalbln$FUNC, false
    );
    static final FunctionDescriptor nearbyint$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle nearbyint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "nearbyint",
            "(D)D",
            constants$60.nearbyint$FUNC, false
    );
    static final FunctionDescriptor __nearbyint$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __nearbyint$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__nearbyint",
            "(D)D",
            constants$60.__nearbyint$FUNC, false
    );
}


