// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$14 {

    static final FunctionDescriptor scanf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle scanf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scanf",
            "(Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
            constants$14.scanf$FUNC, true
    );
    static final FunctionDescriptor sscanf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle sscanf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "sscanf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
            constants$14.sscanf$FUNC, true
    );
    static final FunctionDescriptor vfscanf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle vfscanf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "vfscanf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$14.vfscanf$FUNC, false
    );
    static final FunctionDescriptor vscanf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle vscanf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "vscanf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$14.vscanf$FUNC, false
    );
    static final FunctionDescriptor vsscanf$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle vsscanf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "vsscanf",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$14.vsscanf$FUNC, false
    );
    static final FunctionDescriptor fgetc$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle fgetc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fgetc",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$14.fgetc$FUNC, false
    );
}


