// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$98 {

    static final FunctionDescriptor libraw_unpack_function_name$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_unpack_function_name$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_unpack_function_name",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$98.libraw_unpack_function_name$FUNC, false
    );
    static final FunctionDescriptor libraw_get_decoder_info$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_get_decoder_info$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_decoder_info",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$98.libraw_get_decoder_info$FUNC, false
    );
    static final FunctionDescriptor libraw_COLOR$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_INT,
            C_INT
    );
    static final MethodHandle libraw_COLOR$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_COLOR",
            "(Ljdk/incubator/foreign/MemoryAddress;II)I",
            constants$98.libraw_COLOR$FUNC, false
    );
    static final FunctionDescriptor libraw_capabilities$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle libraw_capabilities$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_capabilities",
            "([Ljava/lang/Object;)I",
            constants$98.libraw_capabilities$FUNC, true
    );
    static final FunctionDescriptor libraw_adjust_sizes_info_only$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_adjust_sizes_info_only$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_adjust_sizes_info_only",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$98.libraw_adjust_sizes_info_only$FUNC, false
    );
    static final FunctionDescriptor libraw_dcraw_ppm_tiff_writer$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_dcraw_ppm_tiff_writer$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_dcraw_ppm_tiff_writer",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$98.libraw_dcraw_ppm_tiff_writer$FUNC, false
    );
}


