// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$111 {

    static final MemorySegment PRIuLEAST32$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuLEAST64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST8$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST16$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST32$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment PRIuFAST64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
}


