// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;
import jdk.incubator.foreign.MemoryLayout;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$90 {

    static final FunctionDescriptor setitimer$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle setitimer$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "setitimer",
            "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$90.setitimer$FUNC, false
    );
    static final FunctionDescriptor utimes$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle utimes$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "utimes",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$90.utimes$FUNC, false
    );
    static final FunctionDescriptor lutimes$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle lutimes$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "lutimes",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$90.lutimes$FUNC, false
    );
    static final FunctionDescriptor futimes$FUNC = FunctionDescriptor.of(C_INT,
            C_INT,
            C_POINTER
    );
    static final MethodHandle futimes$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "futimes",
            "(ILjdk/incubator/foreign/MemoryAddress;)I",
            constants$90.futimes$FUNC, false
    );
    static final FunctionDescriptor imaxabs$FUNC = FunctionDescriptor.of(C_LONG,
            C_LONG
    );
    static final MethodHandle imaxabs$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "imaxabs",
            "(J)J",
            constants$90.imaxabs$FUNC, false
    );
    static final FunctionDescriptor imaxdiv$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
                    C_LONG.withName("quot"),
                    C_LONG.withName("rem")
            ),
            C_LONG,
            C_LONG
    );
    static final MethodHandle imaxdiv$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "imaxdiv",
            "(JJ)Ljdk/incubator/foreign/MemorySegment;",
            constants$90.imaxdiv$FUNC, false
    );
}


