// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$101 {

    static final FunctionDescriptor libraw_set_highlight$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_highlight$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_highlight",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$101.libraw_set_highlight$FUNC, false
    );
    static final FunctionDescriptor libraw_set_fbdd_noiserd$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_fbdd_noiserd$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_fbdd_noiserd",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$101.libraw_set_fbdd_noiserd$FUNC, false
    );
    static final FunctionDescriptor libraw_get_raw_height$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_get_raw_height$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_raw_height",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$101.libraw_get_raw_height$FUNC, false
    );
    static final FunctionDescriptor libraw_get_raw_width$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_get_raw_width$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_raw_width",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$101.libraw_get_raw_width$FUNC, false
    );
    static final FunctionDescriptor libraw_get_iheight$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_get_iheight$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_iheight",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$101.libraw_get_iheight$FUNC, false
    );
    static final FunctionDescriptor libraw_get_iwidth$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_get_iwidth$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_iwidth",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$101.libraw_get_iwidth$FUNC, false
    );
}


