// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$97 {

    static final FunctionDescriptor libraw_cameraList$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle libraw_cameraList$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_cameraList",
            "([Ljava/lang/Object;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$97.libraw_cameraList$FUNC, true
    );
    static final FunctionDescriptor libraw_cameraCount$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle libraw_cameraCount$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_cameraCount",
            "([Ljava/lang/Object;)I",
            constants$97.libraw_cameraCount$FUNC, true
    );
    static final FunctionDescriptor libraw_set_memerror_handler$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_set_memerror_handler$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_memerror_handler",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$97.libraw_set_memerror_handler$FUNC, false
    );
    static final FunctionDescriptor libraw_set_exifparser_handler$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_set_exifparser_handler$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_exifparser_handler",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$97.libraw_set_exifparser_handler$FUNC, false
    );
    static final FunctionDescriptor libraw_set_dataerror_handler$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_set_dataerror_handler$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_dataerror_handler",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$97.libraw_set_dataerror_handler$FUNC, false
    );
    static final FunctionDescriptor libraw_set_progress_handler$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_set_progress_handler$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_progress_handler",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$97.libraw_set_progress_handler$FUNC, false
    );
}


