// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$105 {

    static final MemorySegment PRIdLEAST32$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdLEAST64$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdFAST8$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdFAST16$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdFAST32$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment PRIdFAST64$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
}


