// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$118 {

    static final MemorySegment SCNd8$SEGMENT = CLinker.toCString("hhd", ResourceScope.newImplicitScope());
    static final MemorySegment SCNd16$SEGMENT = CLinker.toCString("hd", ResourceScope.newImplicitScope());
    static final MemorySegment SCNd32$SEGMENT = CLinker.toCString("d", ResourceScope.newImplicitScope());
    static final MemorySegment SCNd64$SEGMENT = CLinker.toCString("ld", ResourceScope.newImplicitScope());
    static final MemorySegment SCNdLEAST8$SEGMENT = CLinker.toCString("hhd", ResourceScope.newImplicitScope());
    static final MemorySegment SCNdLEAST16$SEGMENT = CLinker.toCString("hd", ResourceScope.newImplicitScope());
}


