// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$112 {

    static final MemorySegment PRIx8$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIx16$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIx32$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIx64$SEGMENT = CLinker.toCString("lx", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxLEAST8$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
    static final MemorySegment PRIxLEAST16$SEGMENT = CLinker.toCString("x", ResourceScope.newImplicitScope());
}


