// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$39 {

    static final FunctionDescriptor fcvt$FUNC = FunctionDescriptor.of(C_POINTER,
            C_DOUBLE,
            C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle fcvt$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fcvt",
            "(DILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$39.fcvt$FUNC, false
    );
    static final FunctionDescriptor gcvt$FUNC = FunctionDescriptor.of(C_POINTER,
            C_DOUBLE,
            C_INT,
            C_POINTER
    );
    static final MethodHandle gcvt$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "gcvt",
            "(DILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$39.gcvt$FUNC, false
    );
    static final FunctionDescriptor ecvt_r$FUNC = FunctionDescriptor.of(C_INT,
            C_DOUBLE,
            C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle ecvt_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ecvt_r",
            "(DILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
            constants$39.ecvt_r$FUNC, false
    );
    static final FunctionDescriptor fcvt_r$FUNC = FunctionDescriptor.of(C_INT,
            C_DOUBLE,
            C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle fcvt_r$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fcvt_r",
            "(DILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
            constants$39.fcvt_r$FUNC, false
    );
    static final FunctionDescriptor mblen$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle mblen$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mblen",
            "(Ljdk/incubator/foreign/MemoryAddress;J)I",
            constants$39.mblen$FUNC, false
    );
    static final FunctionDescriptor mbtowc$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_LONG
    );
    static final MethodHandle mbtowc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "mbtowc",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
            constants$39.mbtowc$FUNC, false
    );
}


