// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$109 {

    static final MemorySegment PRIoLEAST32$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoLEAST64$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoFAST8$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoFAST16$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoFAST32$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment PRIoFAST64$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
}


