// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$123 {

    static final MemorySegment SCNuLEAST32$SEGMENT = CLinker.toCString("u", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuLEAST64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuFAST8$SEGMENT = CLinker.toCString("hhu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuFAST16$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuFAST32$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
    static final MemorySegment SCNuFAST64$SEGMENT = CLinker.toCString("lu", ResourceScope.newImplicitScope());
}


