// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;

class constants$88 {

    static final FunctionDescriptor fminf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle fminf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fminf",
            "(FF)F",
            constants$88.fminf$FUNC, false
    );
    static final FunctionDescriptor __fminf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __fminf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fminf",
            "(FF)F",
            constants$88.__fminf$FUNC, false
    );
    static final FunctionDescriptor fmaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle fmaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fmaf",
            "(FFF)F",
            constants$88.fmaf$FUNC, false
    );
    static final FunctionDescriptor __fmaf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __fmaf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fmaf",
            "(FFF)F",
            constants$88.__fmaf$FUNC, false
    );
    static final FunctionDescriptor scalbf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle scalbf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scalbf",
            "(FF)F",
            constants$88.scalbf$FUNC, false
    );
    static final FunctionDescriptor __scalbf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __scalbf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__scalbf",
            "(FF)F",
            constants$88.__scalbf$FUNC, false
    );
}


