// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$106 {

    static final MemorySegment PRIi8$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
    static final MemorySegment PRIi16$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
    static final MemorySegment PRIi32$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
    static final MemorySegment PRIi64$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment PRIiLEAST8$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
    static final MemorySegment PRIiLEAST16$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
}


