// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_LONG;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$7 {

    static final FunctionDescriptor strcasecmp_l$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strcasecmp_l$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strcasecmp_l",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$7.strcasecmp_l$FUNC, false
    );
    static final FunctionDescriptor strncasecmp_l$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER,
            C_LONG,
            C_POINTER
    );
    static final MethodHandle strncasecmp_l$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strncasecmp_l",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
            constants$7.strncasecmp_l$FUNC, false
    );
    static final FunctionDescriptor explicit_bzero$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_LONG
    );
    static final MethodHandle explicit_bzero$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "explicit_bzero",
            "(Ljdk/incubator/foreign/MemoryAddress;J)V",
            constants$7.explicit_bzero$FUNC, false
    );
    static final FunctionDescriptor strsep$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle strsep$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strsep",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$7.strsep$FUNC, false
    );
    static final FunctionDescriptor strsignal$FUNC = FunctionDescriptor.of(C_POINTER,
            C_INT
    );
    static final MethodHandle strsignal$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "strsignal",
            "(I)Ljdk/incubator/foreign/MemoryAddress;",
            constants$7.strsignal$FUNC, false
    );
    static final FunctionDescriptor __stpcpy$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle __stpcpy$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__stpcpy",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$7.__stpcpy$FUNC, false
    );
}


