// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;

class constants$56 {

    static final FunctionDescriptor y1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle y1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "y1",
            "(D)D",
            constants$56.y1$FUNC, false
    );
    static final FunctionDescriptor __y1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __y1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__y1",
            "(D)D",
            constants$56.__y1$FUNC, false
    );
    static final FunctionDescriptor yn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_INT,
            C_DOUBLE
    );
    static final MethodHandle yn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "yn",
            "(ID)D",
            constants$56.yn$FUNC, false
    );
    static final FunctionDescriptor __yn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_INT,
            C_DOUBLE
    );
    static final MethodHandle __yn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__yn",
            "(ID)D",
            constants$56.__yn$FUNC, false
    );
    static final FunctionDescriptor erf$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle erf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "erf",
            "(D)D",
            constants$56.erf$FUNC, false
    );
    static final FunctionDescriptor __erf$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __erf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__erf",
            "(D)D",
            constants$56.__erf$FUNC, false
    );
}


