// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_INT;

class constants$55 {

    static final FunctionDescriptor j1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle j1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "j1",
            "(D)D",
            constants$55.j1$FUNC, false
    );
    static final FunctionDescriptor __j1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __j1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__j1",
            "(D)D",
            constants$55.__j1$FUNC, false
    );
    static final FunctionDescriptor jn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_INT,
            C_DOUBLE
    );
    static final MethodHandle jn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "jn",
            "(ID)D",
            constants$55.jn$FUNC, false
    );
    static final FunctionDescriptor __jn$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_INT,
            C_DOUBLE
    );
    static final MethodHandle __jn$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__jn",
            "(ID)D",
            constants$55.__jn$FUNC, false
    );
    static final FunctionDescriptor y0$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle y0$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "y0",
            "(D)D",
            constants$55.y0$FUNC, false
    );
    static final FunctionDescriptor __y0$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __y0$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__y0",
            "(D)D",
            constants$55.__y0$FUNC, false
    );
}


