// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;

class constants$64 {

    static final FunctionDescriptor fmin$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle fmin$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fmin",
            "(DD)D",
            constants$64.fmin$FUNC, false
    );
    static final FunctionDescriptor __fmin$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __fmin$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fmin",
            "(DD)D",
            constants$64.__fmin$FUNC, false
    );
    static final FunctionDescriptor fma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle fma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fma",
            "(DDD)D",
            constants$64.fma$FUNC, false
    );
    static final FunctionDescriptor __fma$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __fma$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fma",
            "(DDD)D",
            constants$64.__fma$FUNC, false
    );
    static final FunctionDescriptor scalb$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle scalb$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "scalb",
            "(DD)D",
            constants$64.scalb$FUNC, false
    );
    static final FunctionDescriptor __scalb$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __scalb$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__scalb",
            "(DD)D",
            constants$64.__scalb$FUNC, false
    );
}


