// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$121 {

    static final MemorySegment SCNiLEAST32$SEGMENT = CLinker.toCString("i", ResourceScope.newImplicitScope());
    static final MemorySegment SCNiLEAST64$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment SCNiFAST8$SEGMENT = CLinker.toCString("hhi", ResourceScope.newImplicitScope());
    static final MemorySegment SCNiFAST16$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment SCNiFAST32$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
    static final MemorySegment SCNiFAST64$SEGMENT = CLinker.toCString("li", ResourceScope.newImplicitScope());
}


