// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$72 {

    static final FunctionDescriptor __log10f$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __log10f$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__log10f",
            "(F)F",
            constants$72.__log10f$FUNC, false
    );
    static final FunctionDescriptor modff$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_POINTER
    );
    static final MethodHandle modff$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "modff",
            "(FLjdk/incubator/foreign/MemoryAddress;)F",
            constants$72.modff$FUNC, false
    );
    static final FunctionDescriptor __modff$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT,
            C_POINTER
    );
    static final MethodHandle __modff$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__modff",
            "(FLjdk/incubator/foreign/MemoryAddress;)F",
            constants$72.__modff$FUNC, false
    );
    static final FunctionDescriptor expm1f$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle expm1f$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "expm1f",
            "(F)F",
            constants$72.expm1f$FUNC, false
    );
    static final FunctionDescriptor __expm1f$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle __expm1f$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__expm1f",
            "(F)F",
            constants$72.__expm1f$FUNC, false
    );
    static final FunctionDescriptor log1pf$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_FLOAT
    );
    static final MethodHandle log1pf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "log1pf",
            "(F)F",
            constants$72.log1pf$FUNC, false
    );
}


