// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.CLinker;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;

class constants$125 {

    static final MemorySegment SCNoLEAST32$SEGMENT = CLinker.toCString("o", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoLEAST64$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoFAST8$SEGMENT = CLinker.toCString("hho", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoFAST16$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoFAST32$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
    static final MemorySegment SCNoFAST64$SEGMENT = CLinker.toCString("lo", ResourceScope.newImplicitScope());
}


