// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_LONG_LONG;

class constants$63 {

    static final FunctionDescriptor llround$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_DOUBLE
    );
    static final MethodHandle llround$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "llround",
            "(D)J",
            constants$63.llround$FUNC, false
    );
    static final FunctionDescriptor __llround$FUNC = FunctionDescriptor.of(C_LONG_LONG,
            C_DOUBLE
    );
    static final MethodHandle __llround$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__llround",
            "(D)J",
            constants$63.__llround$FUNC, false
    );
    static final FunctionDescriptor fdim$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle fdim$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fdim",
            "(DD)D",
            constants$63.fdim$FUNC, false
    );
    static final FunctionDescriptor __fdim$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __fdim$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fdim",
            "(DD)D",
            constants$63.__fdim$FUNC, false
    );
    static final FunctionDescriptor fmax$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle fmax$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fmax",
            "(DD)D",
            constants$63.fmax$FUNC, false
    );
    static final FunctionDescriptor __fmax$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __fmax$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__fmax",
            "(DD)D",
            constants$63.__fmax$FUNC, false
    );
}


