// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_FLOAT;
import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$102 {

    static final FunctionDescriptor libraw_get_cam_mul$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_get_cam_mul$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_cam_mul",
            "(Ljdk/incubator/foreign/MemoryAddress;I)F",
            constants$102.libraw_get_cam_mul$FUNC, false
    );
    static final FunctionDescriptor libraw_get_pre_mul$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_get_pre_mul$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_pre_mul",
            "(Ljdk/incubator/foreign/MemoryAddress;I)F",
            constants$102.libraw_get_pre_mul$FUNC, false
    );
    static final FunctionDescriptor libraw_get_rgb_cam$FUNC = FunctionDescriptor.of(C_FLOAT,
            C_POINTER,
            C_INT,
            C_INT
    );
    static final MethodHandle libraw_get_rgb_cam$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_rgb_cam",
            "(Ljdk/incubator/foreign/MemoryAddress;II)F",
            constants$102.libraw_get_rgb_cam$FUNC, false
    );
    static final FunctionDescriptor libraw_get_color_maximum$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle libraw_get_color_maximum$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_color_maximum",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$102.libraw_get_color_maximum$FUNC, false
    );
    static final FunctionDescriptor libraw_set_output_tif$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER,
            C_INT
    );
    static final MethodHandle libraw_set_output_tif$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_set_output_tif",
            "(Ljdk/incubator/foreign/MemoryAddress;I)V",
            constants$102.libraw_set_output_tif$FUNC, false
    );
    static final FunctionDescriptor libraw_get_iparams$FUNC = FunctionDescriptor.of(C_POINTER,
            C_POINTER
    );
    static final MethodHandle libraw_get_iparams$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "libraw_get_iparams",
            "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
            constants$102.libraw_get_iparams$FUNC, false
    );
}


