// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_INT;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$20 {

    static final FunctionDescriptor fsetpos$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER,
            C_POINTER
    );
    static final MethodHandle fsetpos$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "fsetpos",
            "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$20.fsetpos$FUNC, false
    );
    static final FunctionDescriptor clearerr$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle clearerr$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "clearerr",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$20.clearerr$FUNC, false
    );
    static final FunctionDescriptor feof$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle feof$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "feof",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$20.feof$FUNC, false
    );
    static final FunctionDescriptor ferror$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle ferror$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "ferror",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$20.ferror$FUNC, false
    );
    static final FunctionDescriptor clearerr_unlocked$FUNC = FunctionDescriptor.ofVoid(
            C_POINTER
    );
    static final MethodHandle clearerr_unlocked$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "clearerr_unlocked",
            "(Ljdk/incubator/foreign/MemoryAddress;)V",
            constants$20.clearerr_unlocked$FUNC, false
    );
    static final FunctionDescriptor feof_unlocked$FUNC = FunctionDescriptor.of(C_INT,
            C_POINTER
    );
    static final MethodHandle feof_unlocked$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "feof_unlocked",
            "(Ljdk/incubator/foreign/MemoryAddress;)I",
            constants$20.feof_unlocked$FUNC, false
    );
}


