// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$48 {

    static final FunctionDescriptor __log10$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __log10$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__log10",
            "(D)D",
            constants$48.__log10$FUNC, false
    );
    static final FunctionDescriptor modf$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle modf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "modf",
            "(DLjdk/incubator/foreign/MemoryAddress;)D",
            constants$48.modf$FUNC, false
    );
    static final FunctionDescriptor __modf$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle __modf$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__modf",
            "(DLjdk/incubator/foreign/MemoryAddress;)D",
            constants$48.__modf$FUNC, false
    );
    static final FunctionDescriptor expm1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle expm1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "expm1",
            "(D)D",
            constants$48.expm1$FUNC, false
    );
    static final FunctionDescriptor __expm1$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __expm1$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__expm1",
            "(D)D",
            constants$48.__expm1$FUNC, false
    );
    static final FunctionDescriptor log1p$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle log1p$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "log1p",
            "(D)D",
            constants$48.log1p$FUNC, false
    );
}


