// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

import static jdk.incubator.foreign.CLinker.C_DOUBLE;
import static jdk.incubator.foreign.CLinker.C_POINTER;

class constants$61 {

    static final FunctionDescriptor round$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle round$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "round",
            "(D)D",
            constants$61.round$FUNC, false
    );
    static final FunctionDescriptor __round$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __round$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__round",
            "(D)D",
            constants$61.__round$FUNC, false
    );
    static final FunctionDescriptor trunc$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle trunc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "trunc",
            "(D)D",
            constants$61.trunc$FUNC, false
    );
    static final FunctionDescriptor __trunc$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE
    );
    static final MethodHandle __trunc$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__trunc",
            "(D)D",
            constants$61.__trunc$FUNC, false
    );
    static final FunctionDescriptor remquo$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle remquo$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "remquo",
            "(DDLjdk/incubator/foreign/MemoryAddress;)D",
            constants$61.remquo$FUNC, false
    );
    static final FunctionDescriptor __remquo$FUNC = FunctionDescriptor.of(C_DOUBLE,
            C_DOUBLE,
            C_DOUBLE,
            C_POINTER
    );
    static final MethodHandle __remquo$MH = RuntimeHelper.downcallHandle(
            libraw_h.LIBRARIES, "__remquo",
            "(DDLjdk/incubator/foreign/MemoryAddress;)D",
            constants$61.__remquo$FUNC, false
    );
}


