// Generated by jextract

package org.libraw;

import jdk.incubator.foreign.Addressable;
import jdk.incubator.foreign.MemoryAddress;
import jdk.incubator.foreign.ResourceScope;

public interface post_identify_callback {

    static MemoryAddress allocate(post_identify_callback fi) {
        return RuntimeHelper.upcallStub(post_identify_callback.class, fi, constants$93.post_identify_callback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)V");
    }

    static MemoryAddress allocate(post_identify_callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(post_identify_callback.class, fi, constants$93.post_identify_callback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }

    static post_identify_callback ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                constants$93.post_identify_callback$MH.invokeExact((Addressable) addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }

    void apply(jdk.incubator.foreign.MemoryAddress x0);
}


